openapi: 3.0.3
info:
  title: Digital Bank API V1
  version: 1.0.0
  description: >-
    Open Connect is a modern, integrated and a highly scalable payment switch
    platform with an efficient service-oriented architecture approach. The
    platform is completely independent and has a multiplayer design. The core
    technology for messaging is based on Queue manager, which is a highly
    scalable MQ system, which can be horizontally scaled to run on a cluster of
    machines. The deployment can be done on Virtual environment as well as
    containerized environment.
  license:
    name: Paysys Labs
    url: https://www.paysyslabs.com/
servers:
  - url: https://apigw.paysyslabs.com/api
    description: Production server
security:
  - jwtToken: []
paths:
  /v1/paysyslabs/token:
    $ref: paths/v1_paysyslabs_token.yaml
  /v1/paysyslabs/payments/unifiedtitlefetch:
    $ref: paths/v1_paysyslabs_payments_unifiedtitlefetch.yaml
components:
  securitySchemes:
    jwtToken:
      type: http
      scheme: bearer
    clientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://apigw.paysyslabs.com/api/v1/paysyslabs/token
          scopes: {}
